permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

# 作者信息
author: 
  name: klone
  email: falcon_sky@yeah.net
  link: http://klone1127.github.io
  weibo: http://weibo.com/klone1127
  github: http://github.com/klone1127
  

# 站点信息
title: 张龙庆的博客
description: My personal blog
url: http://klone1127.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-67577737-1 
  url: http://klone1127.github.io

# disqus 设置
disqus:
  shortname: klone1127

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
# 添加 sitemap
#sitemap:
  path: sitemap.xml
